export const AuditAction = Object.freeze({
  GUILD_CREATED: 'GUILD_CREATED',
  GUILD_DELETED: 'GUILD_DELETED',
  GUILD_REPAIRED: 'GUILD_REPAIRED',
  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  MEMBER_KICKED: 'MEMBER_KICKED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
});
