export const AuditAction = Object.freeze({
  GUILD_CREATED: 'GUILD_CREATED',
  GUILD_DELETED: 'GUILD_DELETED',
  GUILD_REPAIRED: 'GUILD_REPAIRED',
  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  MEMBER_KICKED: 'MEMBER_KICKED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  JOIN_REQUESTED: 'JOIN_REQUESTED',
  JOIN_APPROVED: 'JOIN_APPROVED',
  JOIN_REJECTED: 'JOIN_REJECTED',
  POINTS_CHANGED: 'POINTS_CHANGED',
  LEVEL_UP: 'LEVEL_UP',
  WAR_DECLARED: 'WAR_DECLARED',
  WAR_ACCEPTED: 'WAR_ACCEPTED',
  WAR_DECLINED: 'WAR_DECLINED',
  WAR_FINISHED: 'WAR_FINISHED',
  WAR_CANCELLED: 'WAR_CANCELLED',
});

/** Texto legível de cada ação, usado em /cla logs. */
export const AUDIT_LABEL = Object.freeze({
  GUILD_CREATED: 'clã criado',
  GUILD_DELETED: 'clã excluído',
  GUILD_REPAIRED: 'estrutura reparada',
  MEMBER_INVITED: 'convite enviado',
  MEMBER_JOINED: 'membro entrou',
  MEMBER_LEFT: 'membro saiu',
  MEMBER_KICKED: 'membro removido',
  MEMBER_ROLE_CHANGED: 'cargo interno alterado',
  OWNERSHIP_TRANSFERRED: 'liderança transferida',
  SETTINGS_UPDATED: 'configurações alteradas',
  JOIN_REQUESTED: 'pedido de entrada',
  JOIN_APPROVED: 'pedido aprovado',
  JOIN_REJECTED: 'pedido recusado',
  POINTS_CHANGED: 'pontos alterados',
  LEVEL_UP: 'subiu de nível',
  WAR_DECLARED: 'guerra declarada',
  WAR_ACCEPTED: 'guerra aceita',
  WAR_DECLINED: 'guerra recusada',
  WAR_FINISHED: 'guerra encerrada',
  WAR_CANCELLED: 'guerra cancelada',
});
